### ISSUE TITLE
using codemonstur embedded redis locally working but jenkins jobs are failing giving error

### ISSUE THREAD

**Issue by gouravmodi001** [codemonstur/embedded-redis#29] opened 2024-04-20 18:46 UTC
23:53:42  OrderControllerIntegrationTest > initializationError FAILED
23:53:42      java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:98
23:53:42          Caused by: org.springframework.beans.factory.BeanCreationException at InitDestroyAnnotationBeanPostProcessor.java:160
23:53:42              Caused by: java.io.IOException at RedisInstance.java:51
23:53:42                  Caused by: java.io.IOException at RedisInstance.java:59
23:53:45  
23:53:45  OrderSummaryControllerIntegrationTest > initializationError FAILED
23:53:45      java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:98
23:53:45          Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1804
23:53:45              Caused by: org.apache.kafka.common.KafkaException at SocketServer.scala:778
23:53:45                  Caused by: java.net.BindException at Net.java:-2

**Comment by goruavmodi001** [comment] 2024-04-20 18:47
is there any solution to this?

**Comment by codemonstur** [comment] 2024-04-21 11:50
Possibly, but you have to look at what the actual error is. Your log shows a `Caused by: java.io.IOException at RedisInstance.java:59` but the actual message of the IOException is not included. Line 59 in the latest version of the lib is a comment so you are probably not running that one.

**Comment by dxps** [comment] 2024-05-14 11:28
Hi everyone!

We are facing the same issue (it fails while running on the pipeline agent host), and the exception details are not enough, unfortunately:

```
Caused by: java.io.IOException: Failed to start Redis service
	at redis.embedded.RedisInstance.start(RedisInstance.java:51)
	at my.package.TestRedisConfiguration.postConstruct(TestRedisConfiguration.java:22)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219)
	... 40 more
Caused by: java.io.IOException: Ready pattern not found in log. Startup log: 
	at redis.embedded.RedisInstance.awaitServerReady(RedisInstance.java:59)
	at redis.embedded.RedisInstance.start(RedisInstance.java:45)
	... 45 more
```

What else should we do, please?
Meanwhile, we'll try to figure that out.

Thanks

**Comment by goruavmodi001** [comment] 2024-05-14 11:32
Hi @dxps 
you can use ponfee embedded redis it is also a good library and has no jenkins issue
[https://mvnrepository.com/artifact/cn.ponfee/embedded-redis](url) i have used version 1.2 in my project
hope you are doing fine!!

**Comment by dxps** [comment] 2024-05-14 11:35
@goruavmodi001 

We used the previous version. Now, with ver. 1.4.3 we get enough details! :partying_face: 
The problem is solved (error while loading shared libraries: libssl.so.3).

Thanks anyway for the quick feedback!

**Comment by codemonstur** [comment] 2024-05-14 11:56
@dxps Woot! That was the intention of the change :). So many people keep running into the libssl thing.

@gouravmodi001 Does that mean you have resolved your issue? If so I'll close this ticket.

**Closed** 2024-05-14 11:59 UTC

**Comment by nx-mohammed-rizwan-k** [comment] 2024-12-24 06:20
> The problem is solved (error while loading shared libraries: libssl.so.3).

Hey @dxps , how did you solve the shared library issue ?

**Comment by dxps** [comment] 2024-12-24 08:56
Hey @nx-mohammed-rizwan-k, 
Since I'm on an Ubuntu based Linux distro, I used `sudo apt install libssl3` to install `libssl3` package.

For future reference, you can use https://packages.ubuntu.com/ site: in the _Search the contents of packages_ section, select the Ubuntu base version, type `libssl.so.3` in the keyword input and hit _Search_. And you'll find the package that contains that file.
